name: Frontend PR Checks

on:
  pull_request:
    paths:
      - 'frontend/**'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # ratchet:actions/checkout@v4

      - name: Run htmlhint
        run: npx --yes htmlhint 'frontend/**/*.html'
